from __future__ import annotations

import re
from difflib import SequenceMatcher
from typing import Any, Dict, Optional

from src.llm_client import DeepSeekClient, LLMNotConfigured
from src.schema_index import load_schema
from .generator import _read_prompt


def repair_sql(
    question: str,
    db_id: str,
    schema_context: str,
    failed_sql: str,
    error_message: str,
    *,
    llm_client: Optional[DeepSeekClient] = None,
    model: Optional[str] = None,
    db_path: Optional[str] = None,
) -> Dict[str, Any]:
    heuristic = heuristic_repair_sql(db_id, failed_sql, error_message, db_path=db_path)
    if heuristic:
        return heuristic

    client = llm_client or DeepSeekClient(model=model)
    if not client.available:
        raise LLMNotConfigured("DeepSeek API is not configured; SQL repair is unavailable.")

    messages = [
        {"role": "system", "content": _read_prompt("reflection")},
        {
            "role": "user",
            "content": (
                f"Database id: {db_id}\n"
                f"Question:\n{question}\n\n"
                f"Schema context:\n{schema_context}\n\n"
                f"Failed SQL:\n{failed_sql}\n\n"
                f"Validation or execution error:\n{error_message}\n\n"
                "Return a corrected JSON object."
            ),
        },
    ]
    response = client.json_chat(
        messages,
        cache_parts=[db_id, question, schema_context, failed_sql, error_message],
        model=model,
        task_name="repair_sql",
    )
    parsed = response.parsed or {}
    return {
        "sql": (parsed.get("sql") or "").strip(),
        "reason": parsed.get("reason") or "",
        "confidence": parsed.get("confidence"),
        "source": "llm",
        "cache_hit": response.cache_hit,
        "raw": response.content,
    }


def verify_generated_sql(
    question: str,
    db_id: str,
    schema_context: str,
    generated_sql: str,
    *,
    llm_client: Optional[DeepSeekClient] = None,
    model: Optional[str] = None,
) -> Dict[str, Any]:
    """Ask the LLM to verify a deterministic SQL template result."""

    client = llm_client or DeepSeekClient(model=model)
    if not client.available:
        return {
            "verdict": "skipped",
            "reason": "DeepSeek API is not configured; SQL verification was skipped.",
            "corrected_sql": "",
            "confidence": None,
            "source": "llm",
            "cache_hit": False,
            "raw": "",
        }

    messages = [
        {
            "role": "system",
            "content": (
                "You verify deterministic SQLite SQL generated by an EHR Text-to-SQL system. "
                "Decide whether the SQL answers the question using only the provided schema. "
                "Return JSON only with keys: verdict, reason, corrected_sql, confidence. "
                "verdict must be one of valid, invalid, uncertain. "
                "Only provide corrected_sql when the original SQL is invalid and you can safely fix it. "
                "The corrected SQL must be a single read-only SQLite SELECT query."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Database id: {db_id}\n"
                f"Question:\n{question}\n\n"
                f"Schema context:\n{schema_context}\n\n"
                f"Generated SQL:\n{generated_sql}\n\n"
                "Return the verification JSON now."
            ),
        },
    ]
    response = client.json_chat(
        messages,
        cache_parts=[db_id, question, schema_context, generated_sql],
        model=model,
        task_name="verify_sql",
    )
    parsed = response.parsed or {}
    verdict = str(parsed.get("verdict") or "uncertain").strip().lower()
    if verdict not in {"valid", "invalid", "uncertain"}:
        verdict = "uncertain"
    corrected_sql = (parsed.get("corrected_sql") or parsed.get("sql") or "").strip()
    return {
        "verdict": verdict,
        "reason": parsed.get("reason") or "",
        "corrected_sql": corrected_sql,
        "confidence": parsed.get("confidence"),
        "source": "llm",
        "cache_hit": response.cache_hit,
        "raw": response.content,
    }


def heuristic_repair_sql(
    db_id: str,
    failed_sql: str,
    error_message: str,
    *,
    db_path: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Conservative offline repair for common schema and SQLite errors."""

    try:
        schema = load_schema(db_id, db_path=db_path)
    except Exception:
        return None

    table_names = [table["name"] for table in schema.get("tables", [])]
    columns_by_table = {
        table["name"].lower(): [column["name"] for column in table.get("columns", [])]
        for table in schema.get("tables", [])
    }

    error_lower = error_message.lower()
    if "unknown table" in error_lower:
        repaired = _repair_unknown_tables(failed_sql, error_message, table_names)
        if repaired and repaired != failed_sql:
            return _heuristic_payload(repaired, "Replaced unknown table name with the closest schema table.")

    missing_column = _extract_missing_column(error_message)
    if missing_column:
        repaired = _repair_missing_column(failed_sql, missing_column, table_names, columns_by_table)
        if repaired and repaired != failed_sql:
            return _heuristic_payload(repaired, "Replaced missing column name with the closest schema column.")

        repaired = _quote_bare_filter_value(failed_sql, missing_column, table_names, columns_by_table)
        if repaired and repaired != failed_sql:
            return _heuristic_payload(repaired, "Quoted an unquoted literal in a filter condition.")

    return None


def summarize_result(question: str, sql: str, execution: Dict[str, Any]) -> str:
    if not execution.get("ok"):
        err = execution.get("error") or {}
        return f"Query failed: {err.get('message', 'unknown error')}"
    row_count = execution.get("row_count", 0)
    if row_count == 0:
        return "The query executed successfully but returned no rows."
    columns = execution.get("columns") or []
    rows = execution.get("rows") or []
    preview = rows[:3]
    return f"Returned {row_count} row(s) with columns {columns}. Preview: {preview}"


def _heuristic_payload(sql: str, reason: str) -> Dict[str, Any]:
    return {
        "sql": sql.strip(),
        "reason": reason,
        "confidence": 0.82,
        "source": "heuristic",
        "cache_hit": False,
        "raw": "",
    }


def _repair_unknown_tables(sql: str, error_message: str, table_names: list[str]) -> Optional[str]:
    missing_tables = _extract_unknown_tables(error_message)
    if not missing_tables:
        return None
    repaired = sql
    for missing in missing_tables:
        replacement = _closest_identifier(missing, table_names, aliases={"admission": "admissions"})
        if not replacement:
            return None
        repaired = _replace_identifier(repaired, missing, replacement)
    return repaired


def _repair_missing_column(
    sql: str,
    missing_column: str,
    table_names: list[str],
    columns_by_table: dict[str, list[str]],
) -> Optional[str]:
    table_name, column_name = _split_column_reference(missing_column)
    if not column_name:
        return None

    aliases = {
        "admit_time": "admittime",
        "admission_time": "admittime",
        "discharge_time": "dischtime",
        "gender_code": "gender",
    }

    if table_name:
        table = _closest_identifier(table_name, table_names)
        if not table:
            return None
        replacement_column = _closest_identifier(column_name, columns_by_table.get(table.lower(), []), aliases=aliases)
        if not replacement_column:
            return None
        return _replace_column_reference(sql, table_name, column_name, table, replacement_column)

    referenced_tables = _referenced_tables(sql)
    candidate_columns: list[str] = []
    if len(referenced_tables) == 1:
        table = _closest_identifier(referenced_tables[0], table_names)
        if table:
            candidate_columns = columns_by_table.get(table.lower(), [])
    else:
        for columns in columns_by_table.values():
            candidate_columns.extend(columns)

    replacement_column = _closest_identifier(column_name, candidate_columns, aliases=aliases)
    if not replacement_column:
        return None
    return _replace_identifier(sql, column_name, replacement_column)


def _quote_bare_filter_value(
    sql: str,
    missing_column: str,
    table_names: list[str],
    columns_by_table: dict[str, list[str]],
) -> Optional[str]:
    table_name, value = _split_column_reference(missing_column)
    if table_name or not value or not _looks_like_bare_literal(value):
        return None
    all_columns = {column.lower() for columns in columns_by_table.values() for column in columns}
    if value.lower() in all_columns or value.lower() in {table.lower() for table in table_names}:
        return None

    escaped_value = value.replace("'", "''")
    value_pattern = re.escape(value)
    patterns = [
        re.compile(rf"(?i)(=|<>|!=|like)\s*({value_pattern})(?=\s*(?:$|and\b|or\b|group\b|order\b|limit\b|\)))"),
        re.compile(rf"(?i)(\bin\s*\()\s*({value_pattern})\s*(\))"),
    ]
    repaired = sql
    changed = False

    def replace_binary(match: re.Match[str]) -> str:
        nonlocal changed
        changed = True
        return f"{match.group(1)} '{escaped_value}'"

    repaired = patterns[0].sub(replace_binary, repaired, count=1)
    if changed:
        return repaired

    def replace_in(match: re.Match[str]) -> str:
        nonlocal changed
        changed = True
        return f"{match.group(1)}'{escaped_value}'{match.group(3)}"

    repaired = patterns[1].sub(replace_in, repaired, count=1)
    return repaired if changed else None


def _extract_unknown_tables(error_message: str) -> list[str]:
    match = re.search(r"unknown table\(s\):\s*(.+)$", error_message, flags=re.IGNORECASE)
    if not match:
        return []
    return [part.strip().strip("\"'`[]") for part in match.group(1).split(",") if part.strip()]


def _extract_missing_column(error_message: str) -> Optional[str]:
    match = re.search(r"no such column:\s*([A-Za-z_][A-Za-z0-9_.]*)", error_message, flags=re.IGNORECASE)
    if not match:
        return None
    return match.group(1).strip()


def _split_column_reference(value: str) -> tuple[Optional[str], str]:
    parts = value.split(".")
    if len(parts) >= 2:
        return parts[-2].strip("\"'`[]"), parts[-1].strip("\"'`[]")
    return None, value.strip("\"'`[]")


def _closest_identifier(
    name: str,
    candidates: list[str],
    *,
    aliases: Optional[dict[str, str]] = None,
    cutoff: float = 0.72,
) -> Optional[str]:
    if not name or not candidates:
        return None
    by_lower = {candidate.lower(): candidate for candidate in candidates}
    lowered = name.lower()
    if lowered in by_lower:
        return by_lower[lowered]

    alias_target = (aliases or {}).get(lowered)
    if alias_target and alias_target.lower() in by_lower:
        return by_lower[alias_target.lower()]

    normalized_name = _normalize_identifier(name)
    best_score = 0.0
    best_candidate: Optional[str] = None
    for candidate in candidates:
        score = max(
            SequenceMatcher(None, lowered, candidate.lower()).ratio(),
            SequenceMatcher(None, normalized_name, _normalize_identifier(candidate)).ratio(),
        )
        if score > best_score:
            best_score = score
            best_candidate = candidate
    return best_candidate if best_score >= cutoff else None


def _normalize_identifier(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def _replace_identifier(sql: str, old: str, new: str) -> str:
    pattern = re.compile(rf"(?<![A-Za-z0-9_]){re.escape(old)}(?![A-Za-z0-9_])", flags=re.IGNORECASE)
    return pattern.sub(new, sql)


def _replace_column_reference(
    sql: str,
    old_table: str,
    old_column: str,
    new_table: str,
    new_column: str,
) -> str:
    qualified_pattern = re.compile(
        rf"(?<![A-Za-z0-9_]){re.escape(old_table)}\s*\.\s*{re.escape(old_column)}(?![A-Za-z0-9_])",
        flags=re.IGNORECASE,
    )
    repaired = qualified_pattern.sub(f"{new_table}.{new_column}", sql)
    if repaired != sql:
        return repaired
    return _replace_identifier(sql, old_column, new_column)


def _referenced_tables(sql: str) -> list[str]:
    pattern = re.compile(r"\b(?:from|join)\s+([A-Za-z_][A-Za-z0-9_]*)", flags=re.IGNORECASE)
    return [match.group(1) for match in pattern.finditer(sql)]


def _looks_like_bare_literal(value: str) -> bool:
    if value.lower() in {"null", "true", "false"}:
        return False
    return bool(re.fullmatch(r"[A-Za-z][A-Za-z0-9_ -]*", value))
